# Tensor basics

In [1]:
import numpy as np
import torch

In [2]:
# Creating a zero tensor
x = torch.Tensor(3,4)
print("Type: {}".format(x.type()))
print("Size: {}".format(x.shape))
print("Values: \n{}".format(x))

Type: torch.FloatTensor
Size: torch.Size([3, 4])
Values: 
tensor([[-2.4936e-11,  3.0613e-41,  3.7835e-44,  0.0000e+00],
        [        nan,  0.0000e+00,  1.3733e-14,  6.4069e+02],
        [ 4.3066e+21,  1.1824e+22,  4.3066e+21,  6.3828e+28]])
Type: torch.FloatTensor
Size: torch.Size([3, 4])
Values: 
tensor([[-2.4936e-11,  3.0613e-41,  3.7835e-44,  0.0000e+00],
        [        nan,  0.0000e+00,  1.3733e-14,  6.4069e+02],
        [ 4.3066e+21,  1.1824e+22,  4.3066e+21,  6.3828e+28]])


In [3]:
# Creating a random tensor
x = torch.randn(2,3) # normal distribution (rand(2,3)) -> uniform distribution
print(x)

tensor([[-2.0768,  1.1542,  0.3903],
        [ 0.2189, -0.4617, -1.1241]])
tensor([[-2.0768,  1.1542,  0.3903],
        [ 0.2189, -0.4617, -1.1241]])


In [4]:
# Zero and Ones tensor
x = torch.zeros(2,3)
print(x)
x = torch.ones(2,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [5]:
# List -> Tensor
x = torch.Tensor([[1,2,3], [4,5,6]])
print("Size: {}".format(x.shape))
print("Values: \n{}".format(x))

Size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])
Size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [6]:
# Numpy array -> Tensor
x = torch.from_numpy(np.random.rand(2,3))
print("Size: {}".format(x.shape))
print("Values: \n{}".format(x))

Size: torch.Size([2, 3])
Values: 
tensor([[0.4199, 0.0583, 0.1107],
        [0.7285, 0.3118, 0.2102]], dtype=torch.float64)
Size: torch.Size([2, 3])
Values: 
tensor([[0.4199, 0.0583, 0.1107],
        [0.7285, 0.3118, 0.2102]], dtype=torch.float64)


In [7]:
# Changing tensor type
x = torch.Tensor(3,4)
print("Type: {}".format(x.type()))
x = x.long()
print("Type: {}".format(x.type()))

Type: torch.FloatTensor
Type: torch.LongTensor
Type: torch.FloatTensor
Type: torch.LongTensor


# Tensor operations

In [8]:
# Addition
x = torch.randn(2,3)
y = torch.randn(2,3)
z = x + y
print("Size: {}".format(z.shape))
print("Value: \n{}".format(z))

Size: torch.Size([2, 3])
Value: 
tensor([[-2.1521, -1.2999, -0.6167],
        [-0.0699,  3.0386, -1.3612]])
Size: torch.Size([2, 3])
Value: 
tensor([[-2.1521, -1.2999, -0.6167],
        [-0.0699,  3.0386, -1.3612]])


In [9]:
# Dot product
x = torch.randn(2, 3)
y = torch.randn(3, 2)
z = torch.mm(x, y)
print("Size: {}".format(z.shape))
print("Values: \n{}".format(z))

Size: torch.Size([2, 2])
Values: 
tensor([[ 2.2952,  2.0702],
        [-0.6496, -2.1318]])
Size: torch.Size([2, 2])
Values: 
tensor([[ 2.2952,  2.0702],
        [-0.6496, -2.1318]])


In [10]:
# Transpose
x = torch.randn(2,3)
print("Size: {}".format(x.shape))
print("Values: \n{}".format(x))
y = torch.t(x)
y = x.t()
print("\nSize: {}".format(y.shape))
print("Values: \n{}".format(y))

Size: torch.Size([2, 3])
Values: 
tensor([[ 0.8923,  2.3638, -0.2916],
        [-2.2573, -0.9194,  1.2611]])

Size: torch.Size([3, 2])
Values: 
tensor([[ 0.8923, -2.2573],
        [ 2.3638, -0.9194],
        [-0.2916,  1.2611]])
Size: torch.Size([2, 3])
Values: 
tensor([[ 0.8923,  2.3638, -0.2916],
        [-2.2573, -0.9194,  1.2611]])

Size: torch.Size([3, 2])
Values: 
tensor([[ 0.8923, -2.2573],
        [ 2.3638, -0.9194],
        [-0.2916,  1.2611]])


In [11]:
# Reshape
z = x.view(3, 2)
print("Size: {}".format(z.shape))
print("Values: \n{}".format(z))

Size: torch.Size([3, 2])
Values: 
tensor([[ 0.8923,  2.3638],
        [-0.2916, -2.2573],
        [-0.9194,  1.2611]])
Size: torch.Size([3, 2])
Values: 
tensor([[ 0.8923,  2.3638],
        [-0.2916, -2.2573],
        [-0.9194,  1.2611]])


In [12]:
# Dangers of reshaping (unintended consequences)
x = torch.tensor([
    [[1,1,1,1], [2,2,2,2], [3,3,3,3]],
    [[10,10,10,10], [20,20,20,20], [30,30,30,30]]
])
print("Size: {}".format(x.shape))
print("Values: \n{}\n".format(x))

Size: torch.Size([2, 3, 4])
Values: 
tensor([[[ 1,  1,  1,  1],
         [ 2,  2,  2,  2],
         [ 3,  3,  3,  3]],

        [[10, 10, 10, 10],
         [20, 20, 20, 20],
         [30, 30, 30, 30]]])

Size: torch.Size([2, 3, 4])
Values: 
tensor([[[ 1,  1,  1,  1],
         [ 2,  2,  2,  2],
         [ 3,  3,  3,  3]],

        [[10, 10, 10, 10],
         [20, 20, 20, 20],
         [30, 30, 30, 30]]])



In [13]:
a = x.view(x.size(1), -1) # (dim, dim)
print("Size: {}".format(a.shape))
print("Values: \n{}\n".format(a))

Size: torch.Size([3, 8])
Values: 
tensor([[ 1,  1,  1,  1,  2,  2,  2,  2],
        [ 3,  3,  3,  3, 10, 10, 10, 10],
        [20, 20, 20, 20, 30, 30, 30, 30]])

Size: torch.Size([3, 8])
Values: 
tensor([[ 1,  1,  1,  1,  2,  2,  2,  2],
        [ 3,  3,  3,  3, 10, 10, 10, 10],
        [20, 20, 20, 20, 30, 30, 30, 30]])



In [14]:
b = x.transpose(0, 1).contiguous()
print("Size: {}".format(b.shape))
print("Values: \n{}\n".format(b))

Size: torch.Size([3, 2, 4])
Values: 
tensor([[[ 1,  1,  1,  1],
         [10, 10, 10, 10]],

        [[ 2,  2,  2,  2],
         [20, 20, 20, 20]],

        [[ 3,  3,  3,  3],
         [30, 30, 30, 30]]])

Size: torch.Size([3, 2, 4])
Values: 
tensor([[[ 1,  1,  1,  1],
         [10, 10, 10, 10]],

        [[ 2,  2,  2,  2],
         [20, 20, 20, 20]],

        [[ 3,  3,  3,  3],
         [30, 30, 30, 30]]])



In [15]:
c = b.view(b.size(0), -1)
print("Size: {}".format(c.shape))
print("Values: \n{}\n".format(c))

Size: torch.Size([3, 8])
Values: 
tensor([[ 1,  1,  1,  1, 10, 10, 10, 10],
        [ 2,  2,  2,  2, 20, 20, 20, 20],
        [ 3,  3,  3,  3, 30, 30, 30, 30]])

Size: torch.Size([3, 8])
Values: 
tensor([[ 1,  1,  1,  1, 10, 10, 10, 10],
        [ 2,  2,  2,  2, 20, 20, 20, 20],
        [ 3,  3,  3,  3, 30, 30, 30, 30]])



In [16]:
# Dimensional operations
x = torch.randn(2,3)
print("Values: \n{}".format(x))
y = torch.sum(x, dim=0) # add each row's values for every column
print("Values: \n{}".format(y)) # column's
z = torch.sum(x, dim=1)
print("Values: \n{}".format(z))

Values: 
tensor([[-0.6929, -0.0178, -0.9300],
        [-2.6205,  1.6327, -0.8500]])
Values: 
tensor([-3.3134,  1.6149, -1.7800])
Values: 
tensor([-1.6407, -1.8378])
Values: 
tensor([[-0.6929, -0.0178, -0.9300],
        [-2.6205,  1.6327, -0.8500]])
Values: 
tensor([-3.3134,  1.6149, -1.7800])
Values: 
tensor([-1.6407, -1.8378])


# Indexing, Splicing and Joining

In [17]:
# Select with dimensional indicies
x = torch.randn(2,3)
print("Values: \n{}".format(x))

col_indices = torch.LongTensor([0, 2])
chosen = torch.index_select(x, dim=1, index=col_indices) # values from column 0 & 2
print("Values: \n{}".format(chosen))

row_indices = torch.LongTensor([0, 1])
chosen = x[row_indices, col_indices]
print("Values: \n{}".format(chosen))

Values: 
tensor([[-0.3340, -1.3207, -0.1028],
        [ 0.7539,  0.9419,  0.0532]])
Values: 
tensor([[-0.3340, -0.1028],
        [ 0.7539,  0.0532]])
Values: 
tensor([-0.3340,  0.0532])
Values: 
tensor([[-0.3340, -1.3207, -0.1028],
        [ 0.7539,  0.9419,  0.0532]])
Values: 
tensor([[-0.3340, -0.1028],
        [ 0.7539,  0.0532]])
Values: 
tensor([-0.3340,  0.0532])


In [18]:
# Concatenation
x = torch.randn(2,3)
print("Values: \n{}".format(x))
y = torch.cat([x, x], dim=0)
print("Values: \n{}".format(y))

Values: 
tensor([[ 0.3630,  1.5609, -0.6112],
        [ 0.7135,  0.1509, -1.4686]])
Values: 
tensor([[ 0.3630,  1.5609, -0.6112],
        [ 0.7135,  0.1509, -1.4686],
        [ 0.3630,  1.5609, -0.6112],
        [ 0.7135,  0.1509, -1.4686]])
Values: 
tensor([[ 0.3630,  1.5609, -0.6112],
        [ 0.7135,  0.1509, -1.4686]])
Values: 
tensor([[ 0.3630,  1.5609, -0.6112],
        [ 0.7135,  0.1509, -1.4686],
        [ 0.3630,  1.5609, -0.6112],
        [ 0.7135,  0.1509, -1.4686]])


# Gradients

In [19]:
# Tensors with gradient bookkeeping
x = torch.rand(3, 4, requires_grad=True)
y = 3*x + 2
z = y.mean()
z.backward() # z has to be scalar
print("Values: \n{}".format(x))
print("x.grad: \n", x.grad)

Values: 
tensor([[0.4098, 0.8093, 0.3017, 0.7174],
        [0.1455, 0.9120, 0.8315, 0.4554],
        [0.3838, 0.7130, 0.3170, 0.0651]], requires_grad=True)
x.grad: 
 tensor([[0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500]])
Values: 
tensor([[0.4098, 0.8093, 0.3017, 0.7174],
        [0.1455, 0.9120, 0.8315, 0.4554],
        [0.3838, 0.7130, 0.3170, 0.0651]], requires_grad=True)
x.grad: 
 tensor([[0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500]])


- $ y = 3x + 2 $
- $ z = \frac{\sum y}{N} $
- $ \frac{\partial z}{\partial x} =\frac{\partial z}{\partial y}\frac{\partial y}{\partial x} = \frac{1}{N}*3 = \frac{1}{12} * 3 = 0.25 $

# CUDA tensors

In [20]:
# Is CUDA available?
print(torch.cuda.is_available())

True
True


In [21]:
# Creating a zero tensor
x = torch.Tensor(3,4).to("cpu")
print("Type: {}".format(x.type()))

Type: torch.FloatTensor
Type: torch.FloatTensor


In [22]:
# Creating a zero tensor
x = torch.Tensor(3,4).to("cuda")
print("Type: {}".format(x.type()))

Type: torch.cuda.FloatTensor
Type: torch.cuda.FloatTensor
